version: 2
updates:
  # NuGet package updates
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "chore"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      prefix-development: "chore"

  # GitHub Actions workflow updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
    pull-request-branch-name:
      separator: "-"
    labels:
      - "chore"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
